default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: tacostogram_fonal
  username: tacostogram_fonal_user
  password: <%= ENV["DATABASE_PASSWORD"] %>
  host: dpg-cv89r7l2ng1s73duisr0-a.oregon-postgres.render.com
  port: 5432
  sslmode: require
