default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: tacostogram_fonal
  username: tacostogram_fonal_user
  password: nK8Vg560ed069FMmGMb3r2u00ocKEAvl

